services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build:
      context: ./Frontend/FrontEnd-Neurotype
    ports:
      - "4200:80"
    depends_on:
      - backend
